# Lab 2: Introduction to Python
The purpose of this lab is to familiarize the student with R programming language. However, I don't like R, so I'm just going to demonstrate the same ideas but in Python.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### Making Vectors
`numpy` makes it easy to create vectors in Python. In `numpy` these objects are called arrays, and can be one-dimensional (vectors), 2-dimensional (matrices), or n-dimensional (tensors).

In [2]:
x = np.array([1, 3, 2, 5])
x

array([1, 3, 2, 5])

In [3]:
x = np.array([1, 6, 2])
y = np.array([1, 4, 3])

In [4]:
len(x)

3

In [5]:
len(y)

3

In [6]:
x + y

array([ 2, 10,  5])

`%who` is a magic to see all the variables and aliases that we've defined in our session. Magics can be accessed in `ipython` sessions (including Jupyter).

In [7]:
%who

np	 pd	 plt	 x	 y	 


`%whos` is similar, but it also displays data-type and what the data that the variable contains.

In [8]:
%whos

Variable   Type       Data/Info
-------------------------------
np         module     <module 'numpy' from '/us<...>kages/numpy/__init__.py'>
pd         module     <module 'pandas' from '/u<...>ages/pandas/__init__.py'>
plt        module     <module 'matplotlib.pyplo<...>es/matplotlib/pyplot.py'>
x          ndarray    3: 3 elems, type `int64`, 24 bytes
y          ndarray    3: 3 elems, type `int64`, 24 bytes


`del` removes the definition of the variable totally.

In [9]:
del x, y
%who

np	 pd	 plt	 


Note that `x` and `y` are no longer defined variables in this session.

To get help with a particular object, you can use the `help()` function. The syntax is `help([object])`.

In [10]:
help([np.ndarray])

Help on list object:

class list(object)
 |  list(iterable=(), /)
 |  
 |  Built-in mutable sequence.
 |  
 |  If no argument is given, the constructor creates a new empty list.
 |  The argument must be an iterable if specified.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |  
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate sign

In [11]:
x = np.array([1, 2, 3, 4]).reshape(2,2) # can reshape matrices (call them arrays from now on)
x

array([[1, 2],
       [3, 4]])

In [12]:
x = x.T # can transpose arrays
x

array([[1, 3],
       [2, 4]])

In [13]:
np.sqrt(x)

array([[1.        , 1.73205081],
       [1.41421356, 2.        ]])

In [14]:
x ** 2

array([[ 1,  9],
       [ 4, 16]])